### PR TITLE
Add `eu-west-2`,`eu-west-3` missing regions alongside a custom declaration possibility

### PR DESCRIPTION
**Pull request by iGranDav**
Those Europe regions were missing, and I needed them 🙂

### CODE REVIEW

**Comment by iGranDav** [comment]
I've added a custom declaration to avoid future code based and versioning change when a new region is introduced.

**Comment by iGranDav** [comment]
@BrettRToomey could you please take a look when you have some time?

**Comment by iGranDav** [comment]
Could you please take a look at this?

**Comment by siemensikkema** [comment]
@iGranDav Thanks for your PR! Your addition of a custom case reminded me of a possibly better way to deal with future changes. An enum is almost always problematic when it comes to packages. A more robust way is to use a struct that hides a string in combination with static (computed) variables, like so:

```swift
public struct Region {
    let code: String

    public static var usEast1: Region {
        return .init(code: "us-east-1")
    }

    public static var usEast2: Region {
        return .init(code: "us-east-2")
    }

    public static var usWest1: Region {
        return .init(code: "us-west-1")
    }

    public static var usWest2: Region {
        return .init(code: "us-west-2")
    }

    public static var euWest1: Region {
        return .init(code: "eu-west-1")
    }

    public static var euWest2: Region {
        return .init(code: "eu-west-2")
    }

    public static var euWest3: Region {
        return .init(code: "eu-west-3")
    }

    public static var euCentral1: Region {
        return .init(code: "eu-central-1")
    }

    public static var apSouth1: Region {
        return .init(code: "ap-south-1")
    }

    public static var apSoutheast1: Region {
        return .init(code: "ap-southeast-1")
    }

    public static var apSoutheast2: Region {
        return .init(code: "ap-southeast-2")
    }

    public static var apNortheast1: Region {
        return .init(code: "ap-northeast-1")
    }

    public static var apNortheast2: Region {
        return .init(code: "ap-northeast-2")
    }

    public static var saEast1: Region {
        return .init(code: "sa-east-1")
    }

    public var host: String {
        return "s3-\(code).amazonaws.com"
    }
}
```

**Comment by iGranDav** [comment]
Great idea @siemensikkema! Finally managed to modify it 🙂

**Comment by iGranDav** [comment]
Sure thing 👍 added it! @siemensikkema

**Comment by siemensikkema** [comment]
@iGranDav Thanks!

**Pull request merged**
